-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 15:36:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sis` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `sis` ;

-- -----------------------------------------------------
-- Table `Uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uzivatel` ;

CREATE TABLE IF NOT EXISTS `Uzivatel` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `lastLogin` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Osoba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Osoba` ;

CREATE TABLE IF NOT EXISTS `Osoba` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(100) NOT NULL,
  `prijmeni` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(320) NOT NULL,
  `Uzivatel_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Osoba_Uzivatel1_idx` (`Uzivatel_ID` ASC),
  CONSTRAINT `fk_Osoba_Uzivatel1`
    FOREIGN KEY (`Uzivatel_ID`)
    REFERENCES `Uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uzivatel_has_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uzivatel_has_Role` ;

CREATE TABLE IF NOT EXISTS `Uzivatel_has_Role` (
  `Uzivatel_ID` INT UNSIGNED NOT NULL,
  `Role_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Uzivatel_ID`, `Role_ID`),
  INDEX `fk_Uzivatel_has_Role_Role1_idx` (`Role_ID` ASC),
  INDEX `fk_Uzivatel_has_Role_Uzivatel_idx` (`Uzivatel_ID` ASC),
  CONSTRAINT `fk_Uzivatel_has_Role_Uzivatel`
    FOREIGN KEY (`Uzivatel_ID`)
    REFERENCES `Uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uzivatel_has_Role_Role1`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `Role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Uzivatel`
-- -----------------------------------------------------
START TRANSACTION;
USE `sis`;
INSERT INTO `Uzivatel` (`ID`, `username`, `heslo`, `lastLogin`) VALUES (DEFAULT, 'admin', '$2a$12$Fxrtg1LS13A.06rxusUY5.wOTclvf66qfOcHdseX0642fDhiYgIY2', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `sis`;
INSERT INTO `Role` (`ID`, `nazev`) VALUES (DEFAULT, 'admin');
INSERT INTO `Role` (`ID`, `nazev`) VALUES (DEFAULT, 'vedeni');
INSERT INTO `Role` (`ID`, `nazev`) VALUES (DEFAULT, 'rodic');
INSERT INTO `Role` (`ID`, `nazev`) VALUES (DEFAULT, 'zak');
INSERT INTO `Role` (`ID`, `nazev`) VALUES (DEFAULT, 'ucitel');
INSERT INTO `Role` (`ID`, `nazev`) VALUES (DEFAULT, 'hospodarka');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Uzivatel_has_Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `sis`;
INSERT INTO `Uzivatel_has_Role` (`Uzivatel_ID`, `Role_ID`) VALUES (1, 1);

COMMIT;

